### ISSUE TITLE
Where's part 2?

### ISSUE THREAD

**Issue by vesper8** [amadeus4dev/amadeus-flight-booking-node#18]
Both articles link to Part 1.. and it's a rather short, rather incomplete tutorial.. would love to see part 2.

Also is this sample app fully functional at this point? I'd like to check it out and possibly develop something using your APIs

Cheers

**Comment by tsolakoua** [comment]
Hello @vesper8, thanks for getting in touch! You are right and the part 2 URL has been updated. Regarding the app's functionality some users mentioned they faced trouble running it and it's in our todo to review and update the code. In any case, don't hesitate to raise any specific issues/PRs if you play with the app :)
