### ISSUE TITLE
Calendar shows dates in the past instead of current date

### ISSUE THREAD

**Issue by tsolakoua** [amadeus4dev/amadeus-flight-booking-node#31]
Once you run the app and you go to search for flight, the calendar instead of opening in the current date, it shows May of 2020 for departure and February 2020 for return date. 

Departure date calendar
![Screenshot 2021-09-15 at 17 31 58](https://user-images.githubusercontent.com/15012967/133463635-323386dc-c1da-4311-a808-d3a046d9ed63.png)

Return date calendar
![Screenshot 2021-09-15 at 17 32 52](https://user-images.githubusercontent.com/15012967/133463865-59fcb926-ab13-4dfa-a12d-d3814e910217.png)

The normal behavior would be the calendar to show the current date.

**Comment by ipgpt** [comment]
Hi! I'm ready to help with it
