### ISSUE TITLE
Autocomplete doesn't work

### ISSUE THREAD

**Issue by tsolakoua** [amadeus4dev/amadeus-flight-booking-node#33]
The API uses the Airport & City Search API in order to autocomplete the departure and destination fields. The normal behavior would be while the user types a keyword, to matching cities and airports. 

Instead, there are no suggestions return and below is the error in the console every time a letter is typed in both departure and arrival fields: 

![Screenshot 2021-09-15 at 17 55 06](https://user-images.githubusercontent.com/15012967/133467603-5e7568e0-c20c-4e93-9c56-8a64805f115d.png)

**Comment by ipgpt** [comment]
Hi! I'm ready to help with it
